@Finance.Api_HostAddress = http://localhost:5244


GET {{Finance.Api_HostAddress}}/api/StockSymbol/GetAll
Accept: application/json


###

GET {{Finance.Api_HostAddress}}/api/StockSymbol/GetInternationalSymbols
Accept: application/json

###

GET {{Finance.Api_HostAddress}}/api/StockSymbol/GetEtfSymbols
Accept: application/json

###

GET {{Finance.Api_HostAddress}}/api/StockSymbol/GetCommoditySymbols
Accept: application/json

###

GET {{Finance.Api_HostAddress}}/api/StockSymbol/GetOverTheCounterSymbols
Accept: application/json

###